sudo: required
services:
  - docker

before_install:
  - docker build -t smodi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true smodi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  name: "docker-cra"
  environment: "Dockercra-env"
  bucket_name: "elasticbeanstalk-us-east-2-057520580775"
  bucket_path: "docker-cra"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  